### ISSUE TITLE
Hard crashes with emacs-24 head

### ISSUE THREAD

**Issue by indigoviolet** [byplayer/egg#22]
Steps to repro:
- Build emacs 24 from sources (http://www.emacswiki.org/emacs/EmacsFromGit)
- ./src/emacs -Q -nw
  
  In _scratch_ buffer, add path to github egg checkout
  (add-to-list 'load-path "/home/indigoviolet/.emacs.d/packages/egg")
    (require 'egg)
  
  and eval
  
  visit a file, C-x v s to get status 

hard crash.

**Comment by byplayer** [comment]
It works now.
